### ISSUE TITLE
不能创建项目

### ISSUE THREAD

**Issue by xirtam-ch** [leancloud/node-js-getting-started#15]
美国节点项目

`xirtam:node xirtam$ git clone git@github.com:leancloud/node-js-getting-started.git

Cloning into 'node-js-getting-started'...

ssh: connect to host github.com port 22: Connection refused

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

lean new返回401

**Comment by jysperm** [comment]
命令行工具暂不支持美国节点，预计几天后的下一个版本会支持。

不过你发的这个错误应该是因为无法连接到 Github（`connect to host github.com port 22: Connection refused`）, 建议检查网络连接和代理设置。

**Comment by xirtam-ch** [comment]
lantern ，shadowsocks，vpn都试了，爬墙都没问题，全局也没问题，不知道为何这个项目不行https://github.com/leancloud/node-js-getting-started

**Comment by xirtam-ch** [comment]
hi @jysperm 
在支持美国节点的命令行工具发布之前，我是不是可以用上面的这个github地址创建应用？
现在我可以连接到github
按照https://github.com/leancloud/node-js-getting-started/blob/master/README.md

但是我得到了这个error

`xirtam:node xirtam$ git clone git@github.com:leancloud/node-js-getting-started.git

Cloning into 'node-js-getting-started'...

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by jysperm** [comment]
> 在支持美国节点的命令行工具发布之前，我是不是可以用上面的这个github地址创建应用？

是的，只是尚不支持用命令行部署到美国节点而已，但项目模板都是同样的。

> 但是我得到了这个error

你新发的这个错误是因为没有权限，请确认你已经将你的电脑的 Public Key 添加到了 Github，或者你可以选择使用 https 地址： https://github.com/leancloud/node-js-getting-started.git

**Comment by xirtam-ch** [comment]
3q jysperm
