### ISSUE TITLE
可以创建一个稳定版本的分支?

### ISSUE THREAD

**Issue by liubiqu** [leancloud/node-js-getting-started#17]
现在beta版本实际使用还是有一些问题的，能不能创建一个稳定版本的分支，方便使用。

**Comment by jysperm** [comment]
[Node SDK](https://github.com/leancloud/leanengine-node-sdk) 1.0.0 已经正式地发布了（不再是 beta 了），虽然目前为了兼容性还需要通过 `npm install leanengine@next` 的方式安装，不过我们还是**建议所有新的应用直接使用 1.0.0**，因此示例项目、文档和相关工具也会向 1.0.0 过渡，如果你在使用中遇到问题请联系我们。
