### ISSUE TITLE
下载后执行 avoscloud 提示要添加应用

### ISSUE THREAD

**Issue by lzwjava** [leancloud/node-js-getting-started#2]
![image](https://cloud.githubusercontent.com/assets/5022872/9329312/fdc74b76-45e2-11e5-86db-a151cdda6dd2.png)

需要在 Readme 上补充一下说明或者本地调试不检查 appId，上传的时候再检查。

@sdjcw

**Comment by jysperm** [comment]
本地调试也是需要 appId 才能读写云储存的。
然后新版命令行工具已经会在新建项目时自动关联应用了。

**Comment by lzwjava** [comment]
嗯。

当前 clone 了这个项目后，是要关联应用的。Readme 上补充下较好。

https://github.com/leancloud/node-js-getting-started/pull/8/files
