### ISSUE TITLE
文档过时 AV.Promise._isPromisesAPlusCompliant = false;

### ISSUE THREAD

**Issue by lzwjava** [leancloud/node-js-getting-started#3]
现在似乎改为了这个`AV.Promise._isPromisesAPlusCompliant = false;`

和升级指南的，不一样。升级指南的会提示 undefined。
https://leancloud.cn/docs/leanengine_upgrade_3.html

@sdjcw

**Comment by aisk** [comment]
现在应该使用 AV.Promise.setPromisesAPlusCompliant(false)

**Comment by sdjcw** [comment]
其实任何都不需要设置，现在 js-sdk 会在 Node.js 环境默认就是 false 的设置。
https://github.com/leancloud/javascript-sdk/blob/b62c6dc3ea189c0aa5e1b8d8ff3e56f40f4feacc/lib/promise.js#L56

**Comment by sdjcw** [comment]
@aisk 太过分了，就算是需要更新，你也提交各 PR 把代码修改正确，然后在关闭这个 issue 啊。。。

**Comment by aisk** [comment]
@sdjcw 哦哦看错了……我以为是说这份文档有误，以为已经修复了，刚看到是 getting-started 项目的问题，sorry……
